# Generated by Django 4.0.4 on 2023-03-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_metpolpod_metsven_alter_metgold_dir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetFib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('left', models.FloatField()),
                ('right', models.FloatField()),
                ('exp', models.FloatField()),
                ('dir', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MetKonfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('x_start', models.TextField()),
                ('delta', models.TextField()),
                ('alpha', models.FloatField()),
                ('landa', models.FloatField()),
                ('exp', models.FloatField()),
                ('dir', models.CharField(max_length=3)),
            ],
        ),
    ]
