# Generated by Django 4.0.4 on 2023-03-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_metfib_metkonfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetNap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('x_start', models.TextField()),
                ('n', models.IntegerField()),
                ('exp', models.FloatField()),
                ('dir', models.CharField(max_length=3)),
            ],
        ),
    ]
