# Generated by Django 4.0.4 on 2023-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_metnap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetRan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('x_start', models.TextField()),
                ('nk', models.IntegerField()),
                ('M', models.IntegerField()),
                ('N', models.FloatField()),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('t', models.FloatField()),
                ('R', models.FloatField()),
                ('dir', models.CharField(max_length=3)),
            ],
        ),
    ]
