# Generated by Django 4.0.4 on 2023-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_metran'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('x_vershyny', models.TextField()),
                ('n', models.IntegerField()),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('exp', models.FloatField()),
                ('hamma', models.FloatField()),
                ('dir', models.CharField(max_length=3)),
            ],
        ),
    ]
